spring:
   datasource:
      url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
      username: HR
      password: HR
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format sql: true
   
eureka:
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         defaultzone: http://localhost:8761/eureka
         
         
management:
   endpoints:
      web:
         exposure:
            include:
            - "*"  
